const capitals = {
    'Belarus': 'Minsk',
    'Albania': 'Tirana',
    'Argentina': 'Buenos Aires',
    'Austria': 'Vienna',
    'Belgium': 'Brussels',
    'Brazil': 'Brazilia',
    'Bulgaria': 'Sofia',
    'Canada': 'Ottawa',
    'Chile': 'Santiago',
    'China': 'Beijing',
    'Croatia': 'Zagreb',
    'Cuba': 'Havana',
    'Egypt': 'Cairo',
    'Estonia': 'Tallinn',
    'France': 'Paris',
    'Georgia': 'Tbilisi',
    'Germany': 'Berlin',
    'Greece': 'Athens',
    'Hungary': 'Budapest',
    'Iceland': 'Reykjavik',
    'India': 'New Delhi',
    'Indonesia': 'Jakarta',
    'Iran': 'Tehran',
    'Iraq': 'Baghdad',
    'Ireland': 'Dublin',
    'Italy': 'Rome',
    'Japan': 'Tokyo',
    'Kazakhstan': 'Astana',
    'Kyrgyzstan': 'Bishkek',
    'Latvia': 'Riga',
    'Lithuania': 'Vilnius',
    'Monaco': 'Monaco',
    'Mongolia': 'Ulaanbaatar',
    'Morocco': 'Rabat',
    'Nepal': 'Kathmandu',
    'Netherlands': 'Amsterdam',
    'New Zealand': 'Wellington',
    'Norway': 'Oslo',
    'Poland': 'Warsaw',
    'Portugal': 'Lisbon',
    'Romania': 'Bucharest',
    'Russia': 'Moscow',
    'Serbia': 'Belgrade',
    'Singapore': 'Singapore',
    'Slovakia': 'Bratislava',
    'Slovenia': 'Ljubljana',
    'Spain': 'Madrid',
    'Sweden': 'Stockholm',
    'Switzerland': 'Bern',
    'Syria': 'Damascus',
    'Tajikistan': 'Dushanbe',
    'Thailand': 'Bangkok',
    'Turkey': 'Ankara',
    'Turkmenistan': 'Ashgabat',
    'United Kingdom': '	London',
    'Uzbekistan': 'Tashkent',
    'Vietnam': 'Hanoi'
};

export {capitals};