const listeningArr = {
    './audio/listening/afraid.wav': 'afraid',
    './audio/listening/agree.wav': 'agree',
    './audio/listening/angry.wav': 'angry',
    './audio/listening/arrive.wav': 'arrive',
    './audio/listening/attack.wav': 'attack',
    './audio/listening/clever.wav': 'clever',
    './audio/listening/finally.wav': 'finally',
    './audio/listening/hide.wav': 'hide',
    './audio/listening/hunt.wav': 'hunt',
    './audio/listening/middle.wav': 'middle',
    './audio/listening/moment.wav': 'moment',
    './audio/listening/adventure.wav': 'adventure',
    './audio/listening/approach.wav': 'approach',
    './audio/listening/chemical.wav': 'chemical',
    './audio/listening/create.wav': 'create',
    './audio/listening/evil.wav': 'evil',
    './audio/listening/experiment.wav': 'experiment',
    './audio/listening/kill.wav': 'kill',
    './audio/listening/laboratory.wav': 'laboratory',
    './audio/listening/laugh.wav': 'laugh',
    './audio/listening/loud.wav': 'loud',
    './audio/listening/nervous.wav': 'nervous',
    './audio/listening/noise.wav': 'noise',
    './audio/listening/project.wav': 'project',
    './audio/listening/scare.wav': 'scare',
    './audio/listening/secret.wav': 'secret',
    './audio/listening/shout.wav': 'shout',
    './audio/listening/smell.wav': 'smell',
    './audio/listening/terrible.wav': 'terrible',
};

export {listeningArr};

